"""Regenerating the pack's indexes.

Indexes are **fully rebuilt** every run, never patched. A patched index drifts
from the objects it describes, and drift in a navigation file is the kind of bug
nobody notices for months. Rebuilding is cheap -- a few hundred objects -- and
removes the entire class of problem.

Indexes are derived data. Deleting one and re-running `ke index` must produce
byte-identical output (ADR-0022), which is why every ordering here is explicit.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date
from pathlib import Path

from ke.models import KnowledgeObject

GENERATED_NOTE = (
    "<!-- Generated by `ke index`. Do not edit: this file is rebuilt from the "
    "knowledge objects on every harvest. -->"
)


def _row(obj: KnowledgeObject, relative_path: str) -> str:
    published = obj.published_date.isoformat() if obj.published_date else "—"
    return (
        f"| [{obj.id}]({relative_path}) | {obj.title} | {published} | "
        f"{obj.source_name} |"
    )


def _table(objects: list[tuple[KnowledgeObject, str]]) -> list[str]:
    lines = ["| ID | Title | Published | Source |", "|---|---|---|---|"]
    lines.extend(_row(obj, path) for obj, path in objects)
    return lines


def _sorted(objects: list[tuple[KnowledgeObject, str]]) -> list[tuple[KnowledgeObject, str]]:
    """Newest first, Feature ID as the tiebreaker.

    A total order, so two runs over the same objects cannot disagree.
    """
    return sorted(
        objects,
        key=lambda pair: (
            -(pair[0].published_date or date.min).toordinal(),
            str(pair[0].id),
        ),
    )


def render_index(objects: list[tuple[KnowledgeObject, str]], pack_name: str) -> str:
    ordered = _sorted(objects)
    lines = [
        f"# {pack_name} — knowledge index",
        "",
        GENERATED_NOTE,
        "",
        f"**{len(ordered)} knowledge object(s).**",
        "",
    ]
    lines.extend(_table(ordered))
    lines.append("")
    return "\n".join(lines)


def render_by_source(objects: list[tuple[KnowledgeObject, str]], pack_name: str) -> str:
    grouped: dict[str, list[tuple[KnowledgeObject, str]]] = defaultdict(list)
    for obj, path in objects:
        grouped[obj.source_name].append((obj, path))

    lines = [f"# {pack_name} — by source", "", GENERATED_NOTE, ""]
    for source in sorted(grouped):
        entries = _sorted(grouped[source])
        lines.append(f"## {source} ({len(entries)})")
        lines.append("")
        lines.extend(_table(entries))
        lines.append("")
    return "\n".join(lines)


def render_by_month(objects: list[tuple[KnowledgeObject, str]], pack_name: str) -> str:
    grouped: dict[str, list[tuple[KnowledgeObject, str]]] = defaultdict(list)
    for obj, path in objects:
        grouped[obj.id.month_key].append((obj, path))

    lines = [f"# {pack_name} — by month", "", GENERATED_NOTE, ""]
    for month in sorted(grouped, reverse=True):
        entries = _sorted(grouped[month])
        lines.append(f"## {month} ({len(entries)})")
        lines.append("")
        lines.extend(_table(entries))
        lines.append("")
    return "\n".join(lines)


def render_review_queue(pending: list, pack_name: str) -> str:
    """The queue, as Markdown, so it is visible in the GitHub UI.

    The JSON in `state/` is what the engine reads; this is what a human reads.
    A queue only gets drained if somebody can see it without running a command.
    """
    lines = [
        f"# {pack_name} — review queue",
        "",
        GENERATED_NOTE,
        "",
        f"**{len(pending)} item(s) awaiting review.**",
        "",
        "These were discovered but held back from minting because their identity "
        "could not be trusted enough to create a permanent Feature ID. Nothing "
        "here is lost; run `ke review approve <key>` to release one.",
        "",
    ]
    if not pending:
        lines.append("_Nothing queued._")
        lines.append("")
        return "\n".join(lines)

    lines.extend(["| Key | Title | First seen | Why held |", "|---|---|---|---|"])
    for entry in pending:
        lines.append(
            f"| `{entry.identity_key[7:19]}` | {entry.title} | "
            f"{entry.first_discovered_date.isoformat()} | {entry.reason} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_indexes(
    indexes_dir: Path,
    objects: list[tuple[KnowledgeObject, str]],
    pending: list,
    pack_name: str,
    pack=None,
) -> list[Path]:
    """Rebuild every index. Returns the paths written.

    `review-queue.md` comes from the unified review workflow when a pack is
    supplied, so the file shows every kind of pending decision rather than only
    the items held back from minting.
    """
    indexes_dir.mkdir(parents=True, exist_ok=True)
    if pack is not None:
        from ke.reviewq import render_report

        queue_document = render_report(pack)
    else:
        queue_document = render_review_queue(pending, pack_name)

    documents = {
        "INDEX.md": render_index(objects, pack_name),
        "by-source.md": render_by_source(objects, pack_name),
        "by-month.md": render_by_month(objects, pack_name),
        "review-queue.md": queue_document,
    }

    if pack is not None:
        # Artifact coverage, rebuilt with everything else. Derived data is
        # always regenerated in full rather than patched, so it cannot drift
        # from the objects it describes.
        from ke.artifacts import Coverage, render_index as render_generation_status

        documents["generation-status.md"] = render_generation_status(Coverage.of(pack))
    written = []
    for name, text in documents.items():
        path = indexes_dir / name
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written
